version: "3.1"

services:
  web:
    build:
      context: "_php"
    restart: always
    volumes:
      - ./_php/html:/var/www/html
    links:
      - redis
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./_redis/data:/data